### PR TITLE
Ignore empty line

### PR DESCRIPTION
**Pull request by enniel**
**Problem**

if the response is present ami empty string, the parser generates an error:
`UnexpectedValueExceptionParse error, no colon in line ""`

### CODE REVIEW

**Comment by clue** [comment]
Thanks for your PR @enniel!

I'm currently failing to reproduce this locally, is there any way to reproduce the problem you're seeing?

**Comment by enniel** [comment]
This error occurs when you call the events DongleNewSMSBase64 chan_dongle module.

**Comment by clue** [comment]
This is strange indeed, thanks for spotting!

The parser currently expects a "\r\n\r\n" after every message. If we're going to lift this, I'd suggest we should support parsing the following stream. Does this make sense to you and is this currently possible with your PR?

```
first: 1\r\n
\r\n
second: 2\r\n
\r\n
\r\n
third: 3\r\n
\r\n
\r\n
\r\n
\r\n
fourth: 4\r\n
\r\n
```

**Comment by clue** [comment]
I'm closing this for now due to a lack of feedback. Please come back with more details if you think this is still relevant and we can reopen this :+1:

**Pull request closed without merging**
